### ISSUE TITLE
Design a reusable GDquest UI theme

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-kickstarter-2019#14]
- [ ] Color palette
- [ ] Drawing utilities
- [x] Theme resource

**Comment by razcore-rad** [comment]
Would be useful if you would add a tiny summary or some keywords or something of how it should feel like, even though we probably have a pretty good idea about it already

**Comment by NathanLovato** [comment]
For now I'm looking to build some basic components and set up a template. We can work on a styleguide later. Mostly done for this task with https://github.com/GDquest/kickstarter-quest-3/commit/106fb4c6728ace9ac9dedc1da2fe45e8b251b60e
Only some drawing utils missing
