### ISSUE TITLE
Review Proposals

### ISSUE THREAD

**Issue by razcore-rad** [GDQuest/godot-kickstarter-2019#2]
After worked a bit on ORPG and talking with Nathan I propose these ideas:

- [x] for classes inheriting from Godot objects start with `extends ClassName` followed by `class_name CustomClassName` if necessary, without any newline in between, followed by docstring. The argument is we immediately see what the class is named, followed by the purpose, without any interrupts, it just makes sense to me to have it this way. More on this in the list elements below cause it's all connected.

- [x] leave 2 blank lines between functions and member variables as well as docstring. Rationale is, we group together related pieces of code this way and sometimes it makes sense to have blank lines in functions for grouping logic together. With 2 lines in between it's easier to spot function separation:

```gdscript
extends Node
class_name QuestSystem
"""
Docstring here.
"""
# blank line 1
# blank line 2
onready var timer : Timer = $Timer
onready var pivot : Pivot = $Pivot  # custom class

var some_other_var : = Vector2()
# blank line 1
# blank line 2
func _ready() -> void:
    # do ready stuff
    algorithm(f)
# blank line 1
# blank line 2
func algorithm(input: float) -> void:
    if guard:
        return

    # do some actual work
    return out
# blank line 1
# blank line 2
func another_f() -> Vector2:
    return Vector2()
```

~- [ ] leave 2 spaces between code and comments if on same line (like in pep8 Python recommendation):
`onready var pivot : Pivot = $Pivot␣␣# custom class`, marked here with `␣`~

- [x] declare explicit `onready var` types: `onready var timer : Timer = $Timer` instead of `onready var timer : = $Timer`. Reason is, Godot doesn't seem to auto-cast to correct type and sometimes we have properties calculated at run-time: `onready var size : Vector2 = get_used_rect().size`. In this case, because of `onready` Godot would treat `size` as `Variant` without a type hint, so if you have a calculation depending on it: `var size_px : = path_finder.map.size * path_finder.map.cell_size` it wouldn't know the type, we'd be forced to say: `var size_px : Vector2 = path_finder.map.size * path_finder.map.cell_size`, but if we explicitly declare `onready var` types we won't have any trouble with this.

**Comment by NathanLovato** [comment]
I'm good with almost everything.

1 line between code blocks is from the gdscript styleguide iirc. I used to work with 2 lines at first. It does give you better visual separation.

Regarding two spaces for inline comments: this is one of the things code beautifiers do for you in a typical editor, but that'd be that little extra work to get everyone to do manually. With the syntax highlighting the contrast between the instruction and the comment is clear enough to me:

![image](https://user-images.githubusercontent.com/12694995/51092817-340e2980-17df-11e9-9556-f79d2014a1e4.png)

**Comment by NathanLovato** [comment]
The comments thing is really: if we could automate it definitely! GDscript could really use a code beautifier, also for things like method calls with many parameters, e.g. `Tween.interpolate_*`.

**Comment by razcore-rad** [comment]
Good point, I agree on that one, updated the proposal
