### ISSUE TITLE
Simple BBCode editor for RichTextLabel

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-kickstarter-2019#29]
A minimal bbcode editor for the active selected RichTextLabel node. A text-box to wrap selected text with tags: bold, italic, or color using the palette widget. The text box only needs to display the raw bbcode string.

No need to support detecting existing tags, removing or moving them. Undo is enough to start with. I'd rather like the tool to be ready soon and hopefully get other users to contribute eventually.

It should support shortcuts for the bold and italic functions. E.g. <kbd>Ctrl</kbd><kbd>B</kbd> to bold text.

**Comment by henriiquecampos** [comment]
Will this editor integrate with #23 ? Or will it **also** have its own palette widget?

I mean, shall it have #23 as a dependency somehow?

**Comment by NathanLovato** [comment]
Yes, the idea is it should reuse the palette component. That's why in the palette's issue, I mentioned it shouldn't be hard-coded to set the modulate property of selected nodes but just be a component that returns a color.

By the way when I add "add-on" to the issue, you don't need each of them to be an individual add-on. I hadn't noticed you were doing that at first. We just need one add-on
