### ISSUE TITLE
Convention for functions connected to signals

### ISSUE THREAD

**Issue by razcore-rad** [GDQuest/godot-kickstarter-2019#5]
I rarely connect signals through the GUI so I always find myself wondering about the `all_small_snake_case` when it comes to the signals. I think we can make an exception and use what the GUI offers as default: `_on_NodeName_signal_name`. I used to write `_on_node_name_signal_name`, but I think it's easier in this case just to go with something compatible with what the GUI is doing so we'll make an exception from `all_small_snake_case`.

If someone does end up connecting signals through GUI, he/she'll most likely just accept the default value for the function name, producing `_on_NodeName_signal_name`.

**Comment by razcore-rad** [comment]
I do like following a little "rule" tho'. If the signal is connected to a function in the same object, then strip the name of the Node, eg.: `_on_signal_name` instead of `_on_NodeName_signal_name`

**Comment by NathanLovato** [comment]
That's already how we [try to] do things on ORPG, agreed :)
