### ISSUE TITLE
Learn Godot: Free Guides

### ISSUE THREAD

**Issue by NathanLovato** [GDQuest/godot-kickstarter-2019#52]
See:

1. [Learn Godot: beginners edition](https://github.com/GDquest/GDquest-website/issues/80)
2. [Learn Godot: developers edition](https://github.com/GDquest/GDquest-website/issues/94)

**Comment by NathanLovato** [comment]
The two guides are written now, but they're missing a few things:

- A nice looking banner at the top, and in general an image for when people share the doc on the web
- A handful of pictures to make the page look more alive
- A link to our Discord community at least so people can come and chat, and maybe to the main twitter account

**Comment by razcore-rad** [comment]
Ah, I completely forgot about this after starting to work on the website. I remember I said I'd get the pics, which I did. So we have:

- [x] link to Discord server & official Twitter account
- [x] a handfull of pictures to make the page look more alive
- [x] nice looking banner at the top - this would be a nice opportunity to pull in templates & resources and share them internally. Dropbox/GDrive or anything else could work. This is somewhat related to GDQuest/gdquest-projects#31

Only thing remaining is the banner.
